### PR TITLE
Display items list with rarity

### PR DESCRIPTION
**Pull request by bpierre**
This PR makes use of [loot-rarity](https://github.com/bpierre/loot-rarity) to display the list of items with their respective rarity colors.

This is how it looks (I tried to imitate the style of the bot using on the Loot discord):

One thing that is missing is to retrieve what I think are the OpenSea usernames, but I guess this should be done in another PR anyway. Let me know what you think!

Note: I also added a .prettierrc file.

### CODE REVIEW

**Comment by jpgboi** [comment]
*Note that this bot is not the one used in the #sales channel.*

Hey @bpierre this is awesome!

We talked about including the rarity score in #builders but decided not to because rarity is subjective and not a great metric. I find this approach better and contacted @domhofmann to see what he thinks of it. Hope this will be included when/if this bot will replace the current live one in the discord.

Also, thanks for the `.prettierrc`!

**Comment by bpierre** [comment]
Hey @jpgboi, I didn’t know the plan was to replace the current bot with this one, is there an issue with the one that is used in the discord?

My understanding was that the bot of this repo was meant to be used for other communities (e.g. divine robes), and that the official bot would stay neutral (i.e. without rarity colors), after having asked @domhofmann about this as well.

If the intention is to use this bot in the Loot discord channels and also elsewhere, then maybe I can make the rarity colors an option, let me know. In any cas: I only made these changes because I wanted to test loot-rarity in this context but I really don’t mind if this doesn’t get merged, so don’t worry :hugs:

**Comment by jpgboi** [comment]
Dom gave this a go, gonna merge this soon!

Testing in my own server now and it's super cool. One thing tho: could we make the gray ones a bit whiter to make them more readable? Find it a bit hard to read.

Screen Shot 2021-08-31 at 15 03 57

**Comment by bpierre** [comment]
Awesome! For the grey, I am going to add support in the library to customize the colors, but in the meantime I think we could do this?

```ts
function tweakSvgColors(svg) {
  return svg.replace(/#838383/g, '#aaaaaa')
}

async function rarityImageBuffer(items: string[]): Promise<Buffer> {
  const dataUriImage = imageRarityFromItems(items)
  const svg = tweakSvgColors(
    decodeURIComponent(dataUriImage).split(',')[1]
  )
  return new Promise((resolve, reject) => {
    svg2img(svg, { width: 350, height: 350 }, (err, data) => {
      if (err) reject(err)
      else resolve(data)
    })
  })
}
```

/cc @scotato what would you think of making the grey a tiny bit brighter in loot-rarity + 0xinventory.app?

**Comment by scotato** [comment]
> /cc @scotato what would you think of making the grey a tiny bit brighter in loot-rarity + 0xinventory.app?

sorry I just saw this, i'm down to brighten up the greys

**Comment by bpierre** [comment]
@scotato cool, I’ll try with [`#C0C0C0`](https://github.com/jpgboi/loot-nft-sales-bot/blob/f349886dbaeb7751ce542eb7ad008eaafb86da8e/src/discord.ts#L24), it looks like this (taken from the #sales channel):

**Pull request merged**
